### ISSUE TITLE
Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [seanmonster/CSE142#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington.  A post in this repository contains solution code to our Song homework assignment:

https://github.com/seanmonster/CSE142/blob/master/Song.java

This post's solution code is indexed by Google, enabling current students to easily find it and cheat on their assignments.

Would you please remove this repository or make it private in order to help us enforce our academic policy?

By removing the repository, you would be removing tools that our students could use in academic misconduct.

Thank you, 
Jonathan Sanders
CSE 14X Program Coordinator 
University of Washington 
jsanders@cs.washington.edu

ps, if you sign up with your UW email address, you can get free private repositories https://education.github.com/pack

**Comment by seanmonster** [comment]
Hi Johnathan,

I went ahead and deleted it.

My apologies, I'm not a student at UW, just wanted to work through the curriculum in my own time.

I'll refrain from posting solutions to public repos in the future.

**Comment by jsanders89** [comment]
That's awesome!  Good luck in your studies, and thank you helping us to prevent misconduct! :)
